version: '3.8'

services:
  bang-web-server:
    build:
      context: ../ # point to the parent directory where package.json and source code reside
      dockerfile: docker/Dockerfile # specific path to the Dockerfile
    container_name: bang
    domainname: bang.gbrown.org
    hostname: bang
    networks:
      - node_apps
    ports:
      - "5000:5000"
    tty: true
    restart: unless-stopped
    volumes:
      - ../:/app # mount the parent directory to /app in the container
    command: serve -s /app/dist -l 5000

networks:
  node_apps:
    external: true
