networks:
  default:
    name: ${NETWORK}
    external: true

services:
  bang-web-server:
    env_file:
      - .env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: bang
    domainname: ${DOMAIN}
    networks:
      - default
    hostname: bang
    ports:
      - ${PORT}:${PORT}
    tty: true
    restart: unless-stopped
    volumes:
      - ../:/app
    command: serve -s /app/dist -l 5000
